### ISSUE TITLE
Create black background area for QR codes 

### ISSUE THREAD

**Issue by nicholas-fr** [cta-wave/mezzanine#36] opened 2021-06-22 14:28 UTC
Suggestion from Eurofins to make background of QR code area plain black so that when fading in / out QR codes won't be merged with actual video content. This should help to improve QR code detection.

**Comment by jpiesing** [comment] 2021-06-23 07:26
June 22nd meeting
Proposal to make one test mezzanine stream with the black background so Eurofins can evaluate how much of an improvement it makes to QR code detection.

**Comment by nicholas-fr** [comment] 2021-07-19 15:31
A test mezzanine stream with a black background behind the QR codes can be found here:
https://dash-large-files.akamaized.net/WAVE/Mezzanine/under_review/2021-07-19/
https://dash-large-files.akamaized.net/WAVE/Mezzanine/under_review/2021-07-19/tos_A1_480x270@30_60.mp4

**Comment by nicholas-fr** [comment] 2021-07-20 17:09
@andyburras @yanj-github As discussed in today's call, please review this when you are able and share your feedback. Thanks.

**Comment by jpiesing** [comment] 2021-07-21 19:50
> @andyburras @yanj-github As discussed in today's call, please review this when you are able and share your feedback. Thanks.

To be clear & avoid any mis-understandings, TP Vision does not intend to spend more time on this until we hear from Eurofins.

**Comment by yanj-github** [comment] 2021-07-26 08:29
I have examined 1st 300 frams of this test mezzanine and compare with the one without the black bakgorund on same redording conditions.
With black background: all QR code is detected on 1st scan
Without black background: 25 QR codes missing on 1st scan
Altough with further detection on cropped QR code area, both mezzanines detected all QR codes, more recording frames detected 2 QR codes. 

We think the test mezzanine is better in QR code detection.
Is there a content generated with this test mezzanine going to be generated please? If so we would like to check if this will improve the current time observation.

**Comment by jpiesing** [comment] 2021-07-26 08:32
> Is there a content generated with this test mezzanine going to be generated please? If so we would like to check if this will improve the current time observation.

@yanj-github Would it be enough to generate one piece of test content from this mezzanine? e.g. Stream t1? If yes, please open a github issue in the test content generation & assign it to @rbouqueau

**Comment by yanj-github** [comment] 2021-07-26 08:47
@jpiesing  Yes one content will be good enough for testing. I dont have permission to assigne but the issue is created.

**Comment by cta-source** [comment] 2021-07-26 12:41
> @jpiesing Yes one content will be good enough for testing. I dont have permission to assigne but the issue is created.

I've assigned it to him (@rbouqueau).

**Comment by yanj-github** [comment] 2021-08-02 14:39
Further test summary:

Observations | With black background | Without black background
-- | -- | --
Every sample rendered | Total of missing frames is 4. | Total of missing frames is 212.
currentTime matches | Fail on 14 occasions   Max_time_diff=236.199 | Fail on 5 occasions   Max_time_diff=50.685

This proved that the mezzanine with black background on QR area works better on the detections as well as helps on current time match because more QR code is detected when they are faded in and out.

**Comment by jpiesing** [comment] 2021-08-03 05:41
> This proved that the mezzanine with black background on QR area works better on the detections as well as helps on current time match because more QR code is detected when they are faded in and out.

That's great news.

**Closed as completed** 2021-09-14 09:02 UTC
Labels: Potential-Improvements
